// <auto-generated />
using FotballAPI.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FotballAPI.Migrations
{
    [DbContext(typeof(FotballContext))]
    [Migration("20251129010302_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FotballAPI.Models.Arena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArenaImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArenaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capasity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Arenas");
                });

            modelBuilder.Entity("FotballAPI.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoneyLeft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoneySpendt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfPurchases")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SportsWorld");
                });

            modelBuilder.Entity("FotballAPI.Models.FotballPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Purchased")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FotballPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
